blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/flavius-atticae/shooting-star/tree/main/docs
    about: Check project documentation
  - name: Discussions
    url: https://github.com/flavius-atticae/shooting-star/discussions
    about: Ask questions or discuss ideas
